### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by WLongSAMA** [ArthurHeitmann/MrubyDecompiler#2]
PC File:
data012.cpk\st1\r110.dat\r110_4ebc3b22_scp.bin
data012.cpk\st1\r110.dat\r110_7a562cb9_scp.bin

These two files, converted to rb, unmodified, and then converted to bin, I won't be able to talk to NPCs in the game

![QQ20240715-175007](https://github.com/user-attachments/assets/869641f1-1ea9-4182-a842-084c99dc5025)
![QQ20240715-175024](https://github.com/user-attachments/assets/d12af685-b265-4bfd-88cd-31093461cd34)

[r110(original).zip](https://github.com/user-attachments/files/16232809/r110.original.zip)
[rbfile(NOT MODIFIED).zip](https://github.com/user-attachments/files/16232812/rbfile.NOT.MODIFIED.zip)
[binfile(recompile).zip](https://github.com/user-attachments/files/16232814/binfile.recompile.zip)

[SlotData_2.zip](https://github.com/user-attachments/files/16232816/SlotData_2.zip)

**Comment by ArthurHeitmann** [comment]
I had encountered this issue recently too, but didn't look further into it.
Now I've looked a bit closer and the issue is related to `case`/`when` statements and their `else` part. `case` statements are quite difficult to untangle, but I'll try to come up with a fix.

Problem:
<img width="283" alt="image" src="https://github.com/user-attachments/assets/729fc0cd-6caa-4de7-a3f3-70fb491cff98">

**Comment by WLongSAMA** [comment]
> https://github.com/synspawacza/nier_automata_localization/blob/master/tools/format/bin.py

This script is barely usable, but modifying languages other than English will also give errors.

**Comment by WLongSAMA** [comment]
> I had encountered this issue recently too, but didn't look further into it. Now I've looked a bit closer and the issue is related to `case`/`when` statements and their `else` part. `case` statements are quite difficult to untangle, but I'll try to come up with a fix.
> 
> Problem: <img alt="image" width="283" src="https://private-user-images.githubusercontent.com/37270165/348796057-729fc0cd-6caa-4de7-a3f3-70fb491cff98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDM2NDcsIm5iZiI6MTcyMTEwMzM0NywicGF0aCI6Ii8zNzI3MDE2NS8zNDg3OTYwNTctNzI5ZmMwY2QtNmNhYS00ZGU3LWEzZjMtNzBmYjQ5MWNmZjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA0MTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MWVhYzRhOWI5MzUxYzQzZDQxY2Y2M2E0YWJlNzRjNjY4MGUwNDczYTQ2YTMzZTU1NDI1MTRmNjRiYTg4MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bCTHnniWHcv802JskBRPZIrd_4PGmJWo8AxAzbl2RyM">

Fill in 'call' and it seems to work!
But I don't know if the code logic is complete.
![QQ20240716-124615](https://github.com/user-attachments/assets/18d13454-7441-4b6b-b4ac-a69160866262)
![QQ20240716-124723](https://github.com/user-attachments/assets/8ad8f115-d489-466f-9159-c32cd79cfc98)

**Comment by ArthurHeitmann** [comment]
For that specific function, that is all that is needed. In the meanwhile, I'll try to come up with a fix.
Once it's out, you will have to decompile the original .bin files again and then add your changes to them.

**Comment by WLongSAMA** [comment]
> For that specific function, that is all that is needed. In the meanwhile, I'll try to come up with a fix. Once it's out, you will have to decompile the original .bin files again and then add your changes to them.

Thanks for your help.

**Comment by ArthurHeitmann** [comment]
I've fixed it now and updated it in the latest version of F-SERVO.

If you have any more issue, please let me know.

The following files were previously decompiled incorrectly. To avoid any problems, you will have to restore the origin .bin files and then decompile them. If you've already made any changes to them, make sure to save them somewhere and then apply them again.

data002.cpk/core/corehap.dat/global_5be16b92_scp.bin.rb
data002.cpk/ph1/p100.dat/p100_47a5d6eb_scp.bin.rb
data002.cpk/ph1/p100.dat/p100_4aa7dace_scp.bin.rb
data012.cpk/ph3/p300.dat/p300_4716685f_scp.bin.rb
data012.cpk/ph3/p300.dat/p300_fe415e44_scp.bin.rb
data012.cpk/quest/q330.dat/q330_21f485e_scp.bin.rb
data012.cpk/quest/q330.dat/q330_70a701da_scp.bin.rb
data012.cpk/quest/q330.dat/q330_9bafd382_scp.bin.rb
data012.cpk/quest/q330.dat/q330_b853020f_scp.bin.rb
data012.cpk/quest/q400.dat/q400_1f6199eb_scp.bin.rb
data012.cpk/quest/q400.dat/q400_21ca35cb_scp.bin.rb
data012.cpk/quest/q400.dat/q400_48d76c20_scp.bin.rb
data012.cpk/quest/q400.dat/q400_fc5b48ad_scp.bin.rb
data012.cpk/quest/q550.dat/q550_688e8050_scp.bin.rb
data012.cpk/st1/r110.dat/r110_4ebc3b22_scp.bin.rb
data012.cpk/st1/r110.dat/r110_6b1cbecb_scp.bin.rb
data012.cpk/st1/r110.dat/r110_7a562cb9_scp.bin.rb
data012.cpk/st1/r110.dat/r110_7fe2a715_scp.bin.rb
data012.cpk/st2/r200.dat/r200_d52e3bf5_scp.bin.rb
